@extends('layouts.admin')
@section('title', 'Peran')
@section('subtitle', 'Kelola master peran pengguna.')
@section('content')
@if(session('success'))<div style="background:rgba(38,161,123,0.2);color:var(--gain);padding:12px 16px;border-radius:10px;margin-bottom:24px;font-size:14px;">{{ session('success') }}</div>@endif
@if(session('error'))<div style="background:rgba(194,120,120,0.2);color:var(--loss);padding:12px 16px;border-radius:10px;margin-bottom:24px;font-size:14px;">{{ session('error') }}</div>@endif
<div class="card">
    <div class="card-header"><h2 class="card-title">Daftar Peran</h2><div class="btn-group" style="margin:0;"><button class="btn primary" onclick="document.getElementById('modalTambah').classList.add('active')">+ Tambah Peran</button></div></div>
    <div class="table-wrap"><table class="market-table"><thead><tr><th style="text-align:center;">Nama Peran</th><th style="text-align:center;">Aksi</th></tr></thead>
    <tbody>@foreach($roles as $r)<tr><td class="volume-cell"><span class="coin-name">{{ $r->name }}</span></td><td class="aksi-cell"><button class="btn-aksi edit" onclick="openEdit({{ $r->id }},'{{ addslashes($r->name) }}')">Edit</button><button class="btn-aksi hapus" onclick="openDelete({{ $r->id }},'{{ addslashes($r->name) }}')">Hapus</button></td></tr>@endforeach</tbody></table></div>
</div>
<div class="modal-overlay" id="modalTambah" onclick="if(event.target===this)closeModal('modalTambah')"><div class="modal" style="max-width:420px;"><div class="modal-header"><h2>Tambah Peran</h2><button class="modal-close" onclick="closeModal('modalTambah')">&times;</button></div>
<form method="POST" action="{{ route('roles.store') }}">@csrf<div class="modal-body">
<div class="form-group"><label class="form-label">Nama Peran</label><div class="form-input-wrapper"><input type="text" name="name" class="form-input" placeholder="admin" required></div></div></div>
<div class="modal-footer"><button type="button" class="btn" onclick="closeModal('modalTambah')">Batal</button><button type="submit" class="btn primary">Simpan</button></div></form></div></div>
<div class="modal-overlay" id="modalEdit" onclick="if(event.target===this)closeModal('modalEdit')"><div class="modal" style="max-width:420px;"><div class="modal-header"><h2>Edit Peran</h2><button class="modal-close" onclick="closeModal('modalEdit')">&times;</button></div>
<form method="POST" id="editForm">@csrf @method('PUT')<div class="modal-body">
<div class="form-group"><label class="form-label">Nama Peran</label><div class="form-input-wrapper"><input type="text" name="name" id="editName" class="form-input" required></div></div></div>
<div class="modal-footer"><button type="button" class="btn" onclick="closeModal('modalEdit')">Batal</button><button type="submit" class="btn primary">Simpan Perubahan</button></div></form></div></div>
<div class="modal-overlay" id="modalHapus" onclick="if(event.target===this)closeModal('modalHapus')"><div class="modal" style="max-width:400px;"><div class="modal-header"><h2>Hapus Peran</h2><button class="modal-close" onclick="closeModal('modalHapus')">&times;</button></div>
<div class="modal-body"><p style="color:var(--text-secondary);margin:0;">Yakin ingin menghapus peran <strong id="deleteName"></strong>?</p></div>
<div class="modal-footer"><button type="button" class="btn" onclick="closeModal('modalHapus')">Batal</button><form method="POST" id="deleteForm" style="display:inline;">@csrf @method('DELETE')<button type="submit" class="btn danger">Ya, Hapus</button></form></div></div></div>
@push('styles')<style>.modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,0.6);display:none;align-items:center;justify-content:center;z-index:1000;padding:20px}.modal-overlay.active{display:flex}.modal{background:var(--bg-card);border-radius:16px;width:100%;max-width:480px;max-height:90vh;overflow-y:auto;border:1px solid var(--border-color)}.modal-header{display:flex;align-items:center;justify-content:space-between;padding:20px 24px;border-bottom:1px solid var(--border-color)}.modal-header h2{font-size:18px;font-weight:600;margin:0}.modal-close{background:none;border:none;color:var(--text-secondary);font-size:24px;cursor:pointer;padding:4px 8px;line-height:1}.modal-close:hover{color:var(--text-primary)}.modal-body{padding:24px}.modal-footer{display:flex;gap:12px;justify-content:flex-end;padding:16px 24px;border-top:1px solid var(--border-color)}@media(min-width:769px){.market-table td{text-align:center}}.aksi-cell{white-space:nowrap;text-align:center}.btn-aksi{display:inline-flex;align-items:center;justify-content:center;padding:6px 14px;border:none;border-radius:8px;font-size:12px;font-weight:600;cursor:pointer;transition:all .2s ease;text-decoration:none;margin:0 4px}.btn-aksi.edit{background:rgba(96,165,250,0.15);color:#60a5fa}.btn-aksi.edit:hover{background:rgba(96,165,250,0.3)}.btn-aksi.hapus{background:rgba(239,68,68,0.15);color:#ef4444}.btn-aksi.hapus:hover{background:rgba(239,68,68,0.3)}@media(max-width:1024px){.market-table th:nth-child(2),.market-table td:nth-child(2){display:table-cell!important}}</style>@endpush
@push('scripts')<script>function closeModal(id){document.getElementById(id).classList.remove('active')}function openEdit(id,name){document.getElementById('editForm').action='/roles/'+id;document.getElementById('editName').value=name;document.getElementById('modalEdit').classList.add('active')}function openDelete(id,name){document.getElementById('deleteForm').action='/roles/'+id;document.getElementById('deleteName').textContent=name;document.getElementById('modalHapus').classList.add('active')}</script>@endpush
@endsection