@extends('layouts.admin')
@section('title', 'Laporan Keuangan Bulanan')
@section('subtitle', 'Rekapitulasi pendapatan bulanan dari hasil produksi.')
@section('content')
<div class="card">
    <div class="card-header"><h2 class="card-title">Keuangan Bulanan</h2><form method="GET" style="display:flex;gap:8px;align-items:center;"><div class="form-input-wrapper" style="margin:0;"><input type="month" name="bulan" class="form-input" value="{{ $bulan }}" onchange="this.form.submit()" style="padding:8px 12px;font-size:13px;"></div></form></div>
    <table class="market-table"><thead><tr><th style="text-align:center;">Tanggal</th><th style="text-align:center;">Kandang</th><th style="text-align:center;">Ukuran</th><th style="text-align:center;">Butir</th><th style="text-align:center;">Ikat</th><th style="text-align:center;">Nilai</th><th style="text-align:center;">Total Hari</th></tr></thead>
    <tbody>@if($details->count() > 0)@foreach($details as $tgl => $items)@foreach($items as $i => $d)<tr><td data-label="Tanggal"><div class="coin-cell"><div class="coin-icon btc" style="font-size:12px;">{{ $d->production->tanggal->format('d') }}</div><div><div class="coin-name">{{ $d->production->tanggal->format('d M Y') }}</div></div></div></td><td data-label="Kandang"><div class="coin-cell"><span style="background:var(--accent-copper);color:#fff;border-radius:6px;padding:2px 10px;font-size:12px;font-weight:600;letter-spacing:0.3px;">{{ $d->production->kandang->kode ?? '-' }}</span><div><div class="coin-name" style="font-size:14px;">{{ $d->production->kandang->nama ?? '' }}</div></div></div></td><td data-label="Ukuran" class="volume-cell"><span class="coin-name">{{ $d->eggSize->kode ?? '-' }}</span></td><td data-label="Butir" class="price-cell">{{ number_format($d->jumlah_butir,0,',','.') }}</td><td data-label="Ikat" class="price-cell">{{ number_format($d->jumlah_ikat,0,',','.') }}</td><td data-label="Subtotal" class="price-cell" style="color:var(--gain);">Rp {{ number_format($d->subtotal,0,',','.') }}</td>@if($i === 0)<td data-label="Total Hari" class="price-cell" style="font-weight:600;color:var(--gain);" rowspan="{{ $items->count() }}">Rp {{ number_format($items->sum('subtotal'),0,',','.') }}</td>@endif</tr>@endforeach @endforeach @else<tr><td colspan="7" style="text-align:center;color:var(--text-secondary);padding:32px;">Tidak ada produksi pada bulan ini.</td></tr>@endif</tbody></table>
    @if($details->count() > 0)<div style="padding:16px 24px;border-top:1px solid var(--border-color);display:flex;justify-content:space-between;"><span style="color:var(--text-secondary);">Total Nilai Bulan {{ $bulan }}</span><span style="font-weight:600;color:var(--gain);font-size:18px;">Rp {{ number_format($total,0,',','.') }}</span></div>@endif
</div>
@push('styles')<style>.form-input-wrapper{background:var(--bg-card);border:1px solid var(--border-color);border-radius:10px;display:inline-flex}.form-input-wrapper .form-input{background:none;border:none;color:var(--text-primary);outline:none;width:auto}@media(min-width:769px){.market-table td{text-align:center}}</style>@endpush
@endsection
