@extends('layouts.admin')
@section('title', 'Laporan Produksi per Kandang')
@section('subtitle', 'Rekapitulasi produksi per kandang.')
@section('content')
<div class="card">
    <div class="card-header"><h2 class="card-title">Produksi per Kandang</h2><form method="GET" style="display:flex;gap:8px;align-items:center;"><div class="form-input-wrapper" style="margin:0;"><select name="kandang_id" class="form-input" onchange="this.form.submit()" style="padding:8px 12px;font-size:13px;"><option value="">Pilih kandang</option>@foreach($kandangs as $k)<option value="{{ $k->id }}" {{ $kandangId == $k->id ? 'selected' : '' }}>{{ $k->kode }} - {{ $k->nama }}</option>@endforeach</select></div></form></div>
    @if($kandangId)<table class="market-table"><thead><tr><th style="text-align:center;">Tanggal</th><th style="text-align:center;">Besar</th><th style="text-align:center;">Kecil</th><th style="text-align:center;">Total</th><th style="text-align:center;">Putih</th><th style="text-align:center;">Pecah</th></tr></thead>
    <tbody>@forelse($productions as $p)<tr><td data-label="Tanggal"><div class="coin-cell"><div class="coin-icon btc" style="font-size:12px;">{{ $p->tanggal->format('d') }}</div><div><div class="coin-name">{{ $p->tanggal->format('d M Y') }}</div></div></div></td><td data-label="Besar" class="price-cell">{{ number_format($p->ayam_besar,0,',','.') }}</td><td data-label="Kecil" class="price-cell">{{ number_format($p->ayam_kecil,0,',','.') }}</td><td data-label="Total" class="price-cell" style="font-weight:600;">{{ number_format($p->total_produksi,0,',','.') }}</td><td data-label="Putih" class="price-cell">{{ $p->telur_putih }}</td><td data-label="Pecah" class="price-cell" style="color:var(--loss);">{{ $p->telur_pecah }}</td></tr>@empty<tr><td colspan="6" style="text-align:center;color:var(--text-secondary);padding:32px;">Tidak ada data.</td></tr>@endforelse</tbody></table>
    @if($productions->count() > 0)<div style="padding:16px 24px;border-top:1px solid var(--border-color);display:flex;justify-content:space-between;"><span style="color:var(--text-secondary);">Total</span><span style="font-weight:600;">{{ number_format($productions->sum('total_produksi'),0,',','.') }} butir</span></div>@endif
    @else<div style="padding:32px;text-align:center;color:var(--text-secondary);">Pilih kandang untuk melihat laporan.</div>@endif
</div>
@push('styles')<style>.form-input-wrapper{background:var(--bg-card);border:1px solid var(--border-color);border-radius:10px;display:inline-flex}.form-input-wrapper .form-input{background:none;border:none;color:var(--text-primary);outline:none}@media(min-width:769px){.market-table td{text-align:center}}</style>@endpush
@endsection
