@extends('layouts.admin')
@section('title', 'Kategori Telur')
@section('subtitle', 'Kelola master kategori telur.')
@section('content')
@if(session('success'))<div style="background:rgba(38,161,123,0.2);color:var(--gain);padding:12px 16px;border-radius:10px;margin-bottom:24px;font-size:14px;">{{ session('success') }}</div>@endif
@if(session('error'))<div style="background:rgba(194,120,120,0.2);color:var(--loss);padding:12px 16px;border-radius:10px;margin-bottom:24px;font-size:14px;">{{ session('error') }}</div>@endif
<div class="card">
    <div class="card-header"><h2 class="card-title">Kategori Telur</h2><div class="btn-group" style="margin:0;"><button class="btn primary" onclick="document.getElementById('modalTambah').classList.add('active')">+ Tambah Kategori</button></div></div>
    <div class="search-filters"><div class="search-box"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input type="text" id="searchInput" placeholder="Cari kategori..." oninput="filterTable()"></div></div>
    <table class="market-table"><thead><tr><th style="text-align:center;">Kode</th><th style="text-align:center;">Nama</th><th style="text-align:center;">Unit Penjualan</th><th style="text-align:center;">Urutan</th><th style="text-align:center;">Status</th></tr></thead>
    <tbody>@foreach($categories as $c)<tr><td><div class="coin-cell"><div class="coin-icon btc" style="font-size:13px;">{{ $c->kode }}</div></div></td><td class="volume-cell"><span class="coin-name">{{ $c->nama }}</span></td><td class="price-cell"><span class="coin-name">{{ ucfirst($c->unit_penjualan) }}</span></td><td class="price-cell">{{ $c->urutan }}</td><td class="price-cell"><span class="coin-name" style="color:{{ $c->status === 'Active' ? 'var(--gain)' : 'var(--loss)' }};">{{ $c->status === 'Active' ? 'Aktif' : 'Nonaktif' }}</span></td></tr>@endforeach</tbody></table>
</div>
<div class="modal-overlay" id="modalTambah" onclick="if(event.target===this)closeModal('modalTambah')"><div class="modal" style="max-width:420px;"><div class="modal-header"><h2>Tambah Kategori</h2><button class="modal-close" onclick="closeModal('modalTambah')">&times;</button></div>
<form method="POST" action="{{ route('egg-categories.store') }}">@csrf<div class="modal-body">
<div class="form-group"><label class="form-label">Kode</label><div class="form-input-wrapper"><input type="text" name="kode" class="form-input" placeholder="J" required></div></div>
<div class="form-group"><label class="form-label">Nama</label><div class="form-input-wrapper"><input type="text" name="nama" class="form-input" placeholder="Jumbo" required></div></div>
<div class="form-row"><div class="form-group"><label class="form-label">Unit Penjualan</label><div class="form-input-wrapper"><select name="unit_penjualan" class="form-input" required><option value="papan">Papan</option><option value="ikat">Ikat</option><option value="tidak">Tidak Dijual</option></select></div></div>
<div class="form-group"><label class="form-label">Urutan</label><div class="form-input-wrapper"><input type="number" name="urutan" class="form-input" value="0" min="0" required></div></div></div>
<div class="form-group"><label class="form-label">Status</label><div class="form-input-wrapper"><select name="status" class="form-input" required><option value="Active">Aktif</option><option value="Inactive">Nonaktif</option></select></div></div></div>
<div class="modal-footer"><button type="button" class="btn" onclick="closeModal('modalTambah')">Batal</button><button type="submit" class="btn primary">Simpan</button></div></form></div></div>
<div class="modal-overlay" id="modalEdit" onclick="if(event.target===this)closeModal('modalEdit')"><div class="modal" style="max-width:420px;"><div class="modal-header"><h2>Edit Kategori</h2><button class="modal-close" onclick="closeModal('modalEdit')">&times;</button></div>
<form method="POST" id="editForm">@csrf @method('PUT')<div class="modal-body">
<div class="form-group"><label class="form-label">Kode</label><div class="form-input-wrapper"><input type="text" name="kode" id="editKode" class="form-input" required></div></div>
<div class="form-group"><label class="form-label">Nama</label><div class="form-input-wrapper"><input type="text" name="nama" id="editNama" class="form-input" required></div></div>
<div class="form-row"><div class="form-group"><label class="form-label">Unit Penjualan</label><div class="form-input-wrapper"><select name="unit_penjualan" id="editUnit" class="form-input" required><option value="papan">Papan</option><option value="ikat">Ikat</option><option value="tidak">Tidak Dijual</option></select></div></div>
<div class="form-group"><label class="form-label">Urutan</label><div class="form-input-wrapper"><input type="number" name="urutan" id="editUrutan" class="form-input" min="0" required></div></div></div>
<div class="form-group"><label class="form-label">Status</label><div class="form-input-wrapper"><select name="status" id="editStatus" class="form-input" required><option value="Active">Aktif</option><option value="Inactive">Nonaktif</option></select></div></div></div>
<div class="modal-footer"><button type="button" class="btn" onclick="closeModal('modalEdit')">Batal</button><button type="submit" class="btn primary">Simpan Perubahan</button></div></form></div></div>
<div class="modal-overlay" id="modalHapus" onclick="if(event.target===this)closeModal('modalHapus')"><div class="modal" style="max-width:400px;"><div class="modal-header"><h2>Hapus Kategori</h2><button class="modal-close" onclick="closeModal('modalHapus')">&times;</button></div>
<div class="modal-body"><p style="color:var(--text-secondary);margin:0;">Yakin ingin menghapus <strong id="deleteName"></strong>?</p></div>
<div class="modal-footer"><button type="button" class="btn" onclick="closeModal('modalHapus')">Batal</button><form method="POST" id="deleteForm" style="display:inline;">@csrf @method('DELETE')<button type="submit" class="btn danger">Ya, Hapus</button></form></div></div></div>
@push('styles')<style>.modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,0.6);display:none;align-items:center;justify-content:center;z-index:1000;padding:20px}.modal-overlay.active{display:flex}.modal{background:var(--bg-card);border-radius:16px;width:100%;max-width:480px;max-height:90vh;overflow-y:auto;border:1px solid var(--border-color)}.modal-header{display:flex;align-items:center;justify-content:space-between;padding:20px 24px;border-bottom:1px solid var(--border-color)}.modal-header h2{font-size:18px;font-weight:600;margin:0}.modal-close{background:none;border:none;color:var(--text-secondary);font-size:24px;cursor:pointer;padding:4px 8px;line-height:1}.modal-close:hover{color:var(--text-primary)}.modal-body{padding:24px}.modal-footer{display:flex;gap:12px;justify-content:flex-end;padding:16px 24px;border-top:1px solid var(--border-color)}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:540px){.form-row{grid-template-columns:1fr}.modal{max-width:100%;border-radius:12px}}@media(min-width:769px){.market-table td{text-align:center}}</style>@endpush
@push('scripts')<script>function closeModal(id){document.getElementById(id).classList.remove('active')}function filterTable(){var q=document.getElementById('searchInput').value.toLowerCase();document.querySelectorAll('.market-table tbody tr').forEach(function(r){r.style.display=!q||r.textContent.toLowerCase().includes(q)?'':'none'})}function openEdit(id,kode,nama,unit,urutan,status){document.getElementById('editForm').action='/egg-categories/'+id;document.getElementById('editKode').value=kode;document.getElementById('editNama').value=nama;document.getElementById('editUnit').value=unit;document.getElementById('editUrutan').value=urutan;document.getElementById('editStatus').value=status;document.getElementById('modalEdit').classList.add('active')}function openDelete(id,name){document.getElementById('deleteForm').action='/egg-categories/'+id;document.getElementById('deleteName').textContent=name;document.getElementById('modalHapus').classList.add('active')}</script>@endpush
@endsection
