@extends('layouts.admin')
@section('title', 'Harga Harian')
@section('subtitle', 'Kelola harga telur per ukuran setiap hari.')
@section('content')
@if(session('success'))<div style="background:rgba(38,161,123,0.2);color:var(--gain);padding:12px 16px;border-radius:10px;margin-bottom:24px;font-size:14px;">{{ session('success') }}</div>@endif
@if(session('error'))<div style="background:rgba(194,120,120,0.2);color:var(--loss);padding:12px 16px;border-radius:10px;margin-bottom:24px;font-size:14px;">{{ session('error') }}</div>@endif
<div class="card">
    <div class="card-header"><h2 class="card-title">Semua Harga</h2><div class="btn-group" style="margin:0;"><button class="btn primary" onclick="document.getElementById('modalTambah').classList.add('active')">+ Tambah Harga</button></div></div>
    <div class="search-filters"><div class="search-box"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input type="text" id="searchInput" placeholder="Cari harga..." oninput="filterTable()"></div></div>
    <table class="market-table"><thead><tr><th style="text-align:center;">Tanggal</th><th style="text-align:center;">Ukuran</th><th style="text-align:center;">Harga/Butir</th><th style="text-align:center;">Input Oleh</th><th style="text-align:center;">Aksi</th></tr></thead>
    <tbody>@forelse($prices as $p)<tr><td data-label="Tanggal"><div class="coin-cell"><div class="coin-icon btc" style="font-size:12px;">{{ $p->tanggal->format('d') }}</div><div><div class="coin-name">{{ $p->tanggal->format('d M Y') }}</div></div></div></td><td data-label="Ukuran" class="volume-cell"><span class="coin-name">{{ $p->eggSize->kode }} - {{ $p->eggSize->nama }}</span></td><td data-label="Harga/Butir" class="price-cell" style="color:var(--gain);font-weight:600;">Rp {{ number_format($p->harga_per_butir,0,',','.') }}</td><td data-label="Input Oleh" class="volume-cell" style="color:var(--text-secondary);">{{ $p->creator->name ?? '-' }}</td><td data-label="Aksi" class="text-right"><button class="btn" style="padding:8px 16px;font-size:13px;margin-right:8px;" ontouchstart="event.stopPropagation()" onclick="event.stopPropagation();openEdit({{ $p->id }},'{{ $p->tanggal->format('Y-m-d') }}',{{ $p->egg_size_id }},{{ $p->harga_per_butir }})">Edit</button><button class="btn danger" style="padding:8px 16px;font-size:13px;" ontouchstart="event.stopPropagation()" onclick="event.stopPropagation();openDelete({{ $p->id }},'{{ $p->eggSize->kode }} {{ $p->tanggal->format('d M Y') }}')">Hapus</button></td></tr>@empty<tr><td colspan="5" style="text-align:center;color:var(--text-secondary);padding:32px;">Belum ada data harga.</td></tr>@endforelse</tbody></table>
</div>
<div class="modal-overlay" id="modalTambah" onclick="if(event.target===this)closeModal('modalTambah')"><div class="modal" style="max-width:420px;"><div class="modal-header"><h2>Tambah Harga</h2><button class="modal-close" onclick="closeModal('modalTambah')">&times;</button></div>
<form method="POST" action="{{ route('daily-prices.store') }}">@csrf<div class="modal-body">
<div class="form-group"><label class="form-label">Tanggal</label><div class="form-input-wrapper"><input type="date" name="tanggal" class="form-input" value="{{ now()->format('Y-m-d') }}" required></div></div>
<div class="form-group"><label class="form-label">Ukuran Telur</label><div class="form-input-wrapper"><select name="egg_size_id" class="form-input" required><option value="">Pilih ukuran</option>@foreach($sizes as $s)<option value="{{ $s->id }}">{{ $s->kode }} - {{ $s->nama }}</option>@endforeach</select></div></div>
<div class="form-group"><label class="form-label">Harga Per Butir (Rp)</label><div class="form-input-wrapper"><input type="number" name="harga_per_butir" class="form-input" placeholder="2226" min="0" required></div></div></div>
<div class="modal-footer"><button type="button" class="btn" onclick="closeModal('modalTambah')">Batal</button><button type="submit" class="btn primary">Simpan</button></div></form></div></div>
<div class="modal-overlay" id="modalEdit" onclick="if(event.target===this)closeModal('modalEdit')"><div class="modal" style="max-width:420px;"><div class="modal-header"><h2>Edit Harga</h2><button class="modal-close" onclick="closeModal('modalEdit')">&times;</button></div>
<form method="POST" id="editForm">@csrf @method('PUT')<div class="modal-body">
<div class="form-group"><label class="form-label">Tanggal</label><div class="form-input-wrapper"><input type="date" name="tanggal" id="editTanggal" class="form-input" required></div></div>
<div class="form-group"><label class="form-label">Ukuran Telur</label><div class="form-input-wrapper"><select name="egg_size_id" id="editSize" class="form-input" required><option value="">Pilih ukuran</option>@foreach($sizes as $s)<option value="{{ $s->id }}">{{ $s->kode }} - {{ $s->nama }}</option>@endforeach</select></div></div>
<div class="form-group"><label class="form-label">Harga Per Butir (Rp)</label><div class="form-input-wrapper"><input type="number" name="harga_per_butir" id="editHarga" class="form-input" min="0" required></div></div></div>
<div class="modal-footer"><button type="button" class="btn" onclick="closeModal('modalEdit')">Batal</button><button type="submit" class="btn primary">Simpan Perubahan</button></div></form></div></div>
<div class="modal-overlay" id="modalHapus" onclick="if(event.target===this)closeModal('modalHapus')"><div class="modal" style="max-width:400px;"><div class="modal-header"><h2>Hapus Harga</h2><button class="modal-close" onclick="closeModal('modalHapus')">&times;</button></div>
<div class="modal-body"><p style="color:var(--text-secondary);margin:0;">Yakin ingin menghapus harga <strong id="deleteInfo"></strong>?</p></div>
<div class="modal-footer"><button type="button" class="btn" onclick="closeModal('modalHapus')">Batal</button><form method="POST" id="deleteForm" style="display:inline;">@csrf @method('DELETE')<button type="submit" class="btn danger">Ya, Hapus</button></form></div></div></div>
@push('styles')<style>.modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,0.6);display:none;align-items:center;justify-content:center;z-index:1000;padding:20px}.modal-overlay.active{display:flex}.modal{background:var(--bg-card);border-radius:16px;width:100%;max-width:480px;max-height:90vh;overflow-y:auto;border:1px solid var(--border-color)}.modal-header{display:flex;align-items:center;justify-content:space-between;padding:20px 24px;border-bottom:1px solid var(--border-color)}.modal-header h2{font-size:18px;font-weight:600;margin:0}.modal-close{background:none;border:none;color:var(--text-secondary);font-size:24px;cursor:pointer;padding:4px 8px;line-height:1}.modal-close:hover{color:var(--text-primary)}.modal-body{padding:24px}.modal-footer{display:flex;gap:12px;justify-content:flex-end;padding:16px 24px;border-top:1px solid var(--border-color)}@media(max-width:540px){.modal{max-width:100%;border-radius:12px}}@media(min-width:769px){.market-table td{text-align:center}}</style>@endpush
@push('scripts')<script>function closeModal(id){document.getElementById(id).classList.remove('active')}function filterTable(){var q=document.getElementById('searchInput').value.toLowerCase();document.querySelectorAll('.market-table tbody tr').forEach(function(r){r.style.display=!q||r.textContent.toLowerCase().includes(q)?'':'none'})}function openEdit(id,tgl,sizeId,harga){document.getElementById('editForm').action='/daily-prices/'+id;document.getElementById('editTanggal').value=tgl;document.getElementById('editSize').value=sizeId;document.getElementById('editHarga').value=harga;document.getElementById('modalEdit').classList.add('active')}function openDelete(id,info){document.getElementById('deleteForm').action='/daily-prices/'+id;document.getElementById('deleteInfo').textContent=info;document.getElementById('modalHapus').classList.add('active')}</script>@endpush
@endsection
